version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint files
          command: |
            npm run lint
            npm run lint:ci
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=${TOKEN_NPM_RW}" >> .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          branches:
            ignore: /.*/
          tags:
            only: /^v\d+\.\d+\.\d+?$/
